### ISSUE TITLE
[FEATURE] Better PTF reader

### ISSUE THREAD

**Issue by rzehumat** [manjavacas/melkit#14]

**Comment by rzehumat** [comment]
Both performance and readability of current `ptf.inspect_ptf` and `ptf.MCRBin` are rather bad. I was wondering that utilizing `readptf` from `meltools` might help -- just use [f2py3](https://www.matecdev.com/posts/fortran-in-python.html) and then `PTF` could be read either by Python `MCRBin` or Fortran `readptf`. Finally, benchmark to find which implementation is better.

**Comment by rzehumat** [comment]
I think I could investigate it once #4 is closed.

**Comment by manjavacas** [comment]
Hi @rzehumat, after latest update, I have standarized contributions in order to keep some order in the repo. 

May you rewrite this issue using the new FEATURE issue template? Just re-create it with all this info. The template will be displayed to you.

Thanks in advance, and congrats for your nice job!
